--- 
- hosts: [Client]
  become: yes

  tasks:
    - name: install postgresql
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - postgresql
          - postgresql-contrib
        state: present 

    - name: Update /etc/postgresql/10/main/postgresql.conf
      lineinfile:
        path: /etc/postgresql/10/main/postgresql.conf
        regexp: "#listen_addresses = 'localhost'"
        line: "listen_addresses = '*'"
    
    - name: Update /etc/postgresql/10/main/pg_hba.conf
      lineinfile:
        path: /etc/postgresql/10/main/pg_hba.conf
        regexp: "host    all             all             127.0.0.1/32            md5"
        line: "host    all             all             0.0.0.0/0               md5"
  
    - name: Change postgres password
      shell: sudo -u postgres psql -c "ALTER USER postgres WITH password 'BIRDWelcome@123'"
           

    - name: start postgresql server
      service:
        enabled: yes
        name: postgresql
        state: restarted
